### Site Settings ###
title               : Philip Leindecker
description         : >-                               # >- means to ignore newlines until "url:"
                      Hello World!

url                 : ""                               # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : "/"                              # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : philipleindecker/philipleindecker.github.io    # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]

### Author Info ###
author:
  name              : Philip Leindecker
  image             : /assets/logo.jpg
# behance           : your_username
# dribbble          : your_username
  email             : philip.leindecker@gmail.com
# facebook          : your_username
  github            : philipleindecker
# gitlab            : your_username
# instagram         : your_username
  linkedin          : philip-leindecker-8394b1143
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name


### Pagination ###
paginate: 6
paginate_path: "/articles/page-:num/"


### Posts Permalink ###
permalink: articles/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "post"


### Exclude from processing ###
exclude:
- README.md
- Gemfile
- Gemfile.lock
- articles
